spring:
  mustache:
    cache: false
    suffix: .html
    expose-request-attributes: true
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: postgres